# https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  entrypoint = ["./tmp/main.exe"]

  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]

  log = "build-errors.log"
  stop_on_error = true
  send_interrupt = true
  kill_delay = "500ms"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true
